### ISSUE TITLE
Enhance authorize Middleware to Include Role-Based Access Control

### ISSUE THREAD

**Issue by BomanStatic** [Ehnwall/Filmvisarna#35]
The current authorize middleware in jwtfilter.js verifies the JWT token and attaches the user information to the request object. However, it does not enforce role-based access control. We need to enhance this middleware to accept a user role as a parameter and restrict access to the endpoint based on the user's role. This will ensure that only users with the appropriate roles can access certain resources.

**Comment by AwE9800** [comment]
Fixat
